[package]
name = "progred"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.30"
egui = "0.30"
im = "15"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
