[package]
name = "progred_graph"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4", "serde"] }
ordered-float = { version = "5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
im = "15"
